### ISSUE TITLE
npm install fail 

### ISSUE THREAD

**Issue by allenm** [vsavkin/essential-angular-book-app#1]
npm ERR! peerinvalid The package webpack@2.1.0-beta.25 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @ngtools/webpack@1.2.3 wants webpack@2.2.0-rc.3
npm ERR! peerinvalid Peer extract-text-webpack-plugin@2.0.0-beta.4 wants webpack@^2.1.0-beta.19
npm ERR! peerinvalid Peer html-webpack-plugin@2.26.0 wants webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc
npm ERR! peerinvalid Peer karma-webpack@1.8.1 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta || ^2.2.0-rc
npm ERR! peerinvalid Peer sass-loader@4.1.1 wants webpack@^2 || ^2.2.0-rc.0 || ^2.1.0-beta || ^1.12.6
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.9 wants webpack@^2.1.0-beta

**Comment by rustan-id** [comment]
I got the same issue when trying to install...

$ git clone https://github.com/vsavkin/router_mailapp.git
Cloning into 'router_mailapp'...
remote: Counting objects: 487, done.
remote: Total 487 (delta 0), reused 0 (delta 0), pack-reused 487
Receiving objects: 100% (487/487), 59.77 KiB | 0 bytes/s, done.
Resolving deltas: 100% (277/277), done.

$ cd router_mailapp/

$ npm install
npm WARN deprecated angular-cli@1.0.0-beta.24: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@3.13.1 install /home/gmaimunah/Documents/Angular/Angular Router/router_mailapp/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/gmaimunah/.npm/node-sass/3.13.1/linux-x64-48_binding.node

> fsevents@1.1.2 install /home/gmaimunah/Documents/Angular/Angular Router/router_mailapp/node_modules/fsevents
> node install


> node-sass@3.13.1 postinstall /home/gmaimunah/Documents/Angular/Angular Router/router_mailapp/node_modules/node-sass
> node scripts/build.js

Binary found at /home/gmaimunah/Documents/Angular/Angular Router/router_mailapp/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @angular/compiler-cli@2.4.10 requires a peer of @angular/compiler@2.4.10 but none was installed.
npm WARN @angular/compiler-cli@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @ngtools/webpack@1.4.1 requires a peer of webpack@^2.2.0 but none was installed.
npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none was installed.
npm WARN tslint-loader@3.5.3 requires a peer of tslint@>=4.0.0 but none was installed.

added 1164 packages in 181.624s

$ ng serve
Unable to find "@angular/cli" in devDependencies.

The package "angular-cli" has been deprecated and renamed to "@angular/cli".

Please take the following steps to avoid issues:
**"npm uninstall --save-dev angular-cli"
"npm install --save-dev @angular/cli@latest"** 

The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by DSinkov** [comment]
the same error, after doing recomended by npm steps, this issue converts into
$ ng serve
Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\work\temp\essential-angular-book-app\node_modules\html-webpack-plugin\lib\compiler.js:11:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\work\temp\essential-angular-book-app\node_modules\html-webpack-plugin\index.js:7:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
